### ISSUE TITLE
'ascii' codec can't encode character u'\xea' in position 21: ordinal not in range(128)

### ISSUE THREAD

**Issue by felinto-dev** [HXLStandard/hxl-hashtag-chooser#2]
Hello,

Congratulations on the amazing project! I need to make a specialist system for AI college and I was trying to use yours as a base but when I tried to run it here I got this error:

```
emers@DESKTOP-QNKQ23K MINGW64 ~/Documents/assistente-hashtags-hxl (master)
$ python gen-chooser.py >> docs/index.html
Traceback (most recent call last):
  File "gen-chooser.py", line 123, in <module>
    display_question("top")
  File "gen-chooser.py", line 34, in display_question
    print("      <h2>{}</h2>".format(esc(question["question"])))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xea' in position 21: ordinal not in range(128)
```

Due to another problem I also had when trying to run the file, I had to add this at the beginning of it:

`# encoding=utf8
`
I'm using Python 2.7 because that's what I deduced that you were using. If you're using another, tell me.

Can you give me more details on which python version you used to run these commands or what operating system are you using?

**Comment by davidmegginson** [comment]
Thank you for trying it out. The project requires Python 3.x — I'll mention that in the docs, and add a check in the script.

**Comment by felinto-dev** [comment]
Thank you!
