### ISSUE TITLE
Telegram BOT for this Project

### ISSUE THREAD

**Issue by felinto-dev** [HXLStandard/hxl-hashtag-chooser#3]
Hello!

I created a project based on your idea, but using a Telegram BOT. If you have time, call me on Telegram @felinto so we can exchange some ideas on possible translations and the use of a shared KB :)

Thanks =)

https://github.com/felinto-dev/hxl-hashtag-chooser-bot

**Comment by davidmegginson** [comment]
It looks really interesting! I have some presentations to give tomorrow, but will take a close look later this week. Thanks for letting me know.
